name: CI

on:
  push:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite
          coverage: none
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
      - name: Copy .env and generate key
        run: cp .env.example .env && php artisan key:generate
      - name: Install NPM dependencies
        run: npm install
      - name: Compile assets
        run: npm run build
      - name: Execute tests
        run: php artisan test --filter Feature